image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
    - build
    - test

variables:
    proj: "AdventOfCode"

before_script:
    - "cd $proj"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "dotnet test"
